# Taken from https://github.com/tilt-dev/tilt-helm-demo/blob/d555fabbb1b3110582fb9d4f4e59c7d2ea337d37/values-dev.yaml.
image:
  repository: newrelic-k8s-metrics-adapter
  tag: latest
  pullPolicy: Never

restartPolicy: Never

config:
  externalMetrics:
    # This metric is used in e2e tests.
    e2e:
      query: "select 0.123 from NrUsage"
