global:
  cluster: test-cluster

personalAPIKey: "a21321"
verboseLog: false

config:
  accountID: 111
  region: EU
  nrdbClientTimeoutSeconds: 30

image:
  repository: e2e/newrelic-metrics-adapter
  tag: "test"  # Defaults to AppVersion

resources:
  requests:
    cpu: 15m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 128Mi